#FROM eclipse-temurin:21
#
#LABEL maintainer="mailing4vikash@gmail.com" \
#      version="v1.0" \
#      description="Accounts Microservice of Bank of Noida"
#
#COPY target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar
#
#EXPOSE 8080
#
#ENTRYPOINT ["java", "-jar", "accounts-0.0.1-SNAPSHOT.jar"]
#
#
#
#
# Using Google Jib now to generate dokcer images instead of using dockerfile
