#FROM eclipse-temurin:21
#
#LABEL maintainer="mailing4vikash@gmail.com" \
#      version="v1.0" \
#      description="Loans Microservice of Bank of Noida"
#
#COPY target/loans-0.0.1-SNAPSHOT.jar loans-0.0.1-SNAPSHOT.jar
#
#EXPOSE 8080
#
#ENTRYPOINT ["java", "-jar", "loans-0.0.1-SNAPSHOT.jar"]
#
#
#
#
# Using Google Jib now to create docker images instead of using a docker file
