server:
  port: 8080

spring:
  profiles:
    active:
      - "prod"


  application:
    name:
      accounts
  sql:
    init:
      mode: always

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bank_of_noida
    username: postgres
    password: 42069
    driverClassName: org.postgresql.Driver

build:
  version: "v1.0-dev"

accounts:
  message: "Welcome to Bank of Noida - accounts"
  contactDetails:
    name: "Vikash Pratap Singh - CEO"
    email: "mailing4vikash@gmail.com"
  onCallSupport:
    -(+91) 9865147210
    -(+91) 8798563017



####################################################
#spring:
#  application:
#    name: accounts
#
#  datasource:
#    url: jdbc:postgresql://my-postgres:5432/postgres
#    username: postgres
#    password: 42069
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    database: postgresql
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#
#  sql:
#    init:
#      mode: never
#####################################################
#spring.application.name=accounts
#
#spring.sql.init.mode=never
#
#spring.jpa.database=POSTGRESQL
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=none
#
#spring.datasource.platform=postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/bank_of_noida
#spring.datasource.username=postgres
#spring.datasource.password=42069
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#server.port=8080

######################################################

